name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache CMake dependencies 
        uses: actions/cache@4

        with:
          path: build/_deps
          key: ${{ runner.03 }}-deps-${{ hashFiles(
            'CMakeLists.txt') }}



      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake clang libssl-dev ccache

      - name: configure
        run: |
          cmake -B build -S .

      - name: build
        run: |
          MAKEFLAGS="-j$(nproc)" cmake --build build --verbose


