name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build

          key: ${{ runner.os }}-deps-${{ github.sha}}
          restore-keys: |
              ${{ runner.os }}-build-

      - name: Cache CMake dependencies
        uses: actions/cache@v4

        with:
          path: build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('CMakeLists.txt') }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake clang libssl-dev ccache

      - name: set ccache
        run: |
          echo "CC=ccache clang" >> $GITHUB_ENV
          echo "CXX=ccache clang++" >> $GITHUB_ENV

      - name: configure
        run: |
          ccache cmake -B build -S .
   
      - name: build
        run: |
          ccache cmake --build build --parallel $(nproc)

      - name: getbackExec
        uses: actions/upload-artifact@v4
        with:
          name: MarketEngineExecLinux
          path: build/MarketEngine
